name: Deploy React frontend to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'     # no cache-dependency-path (works even without lockfile)

      - name: Install deps
        working-directory: frontend
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      # If your site will be under https://<user>.github.io/<repo>/ keep PUBLIC_URL.
      # If you use a custom domain (viridata.eu) and add CNAME, you can drop PUBLIC_URL.
      - name: Build
        working-directory: frontend
        env:
          PUBLIC_URL: "/${{ github.event.repository.name }}"
        run: |
          # If your package.json uses CRACO, it should have "build": "craco build"
          # otherwise standard CRA uses "react-scripts build"
          npm run build

      - name: Add 404.html for SPA fallback
        working-directory: frontend
        run: cp build/index.html build/404.html

      # (Optional) If you’re switching to viridata.eu now, uncomment:
      # - name: Add CNAME
      #   working-directory: frontend
      #   run: echo "viridata.eu" > build/CNAME

      - name: Upload artifact (frontend/build)
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
